version: "3"

services:
  airflow:
    build:
      context: .
      dockerfile: ./dockers/airflow/Dockerfile
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - 8080:8080
    environment:
      - AIRFLOW__CORE__FERNET_KEY=PeszOD9t6wKNdNONTGh-k4qsYbsGHQ8CSqTQZlqPCDk=
      - AIRFLOW_HOME=/opt/airflow
    restart: unless-stopped
    # command: sleep infinity
    command: sh /run.sh
